name: Test Scheduler Alone

on: 
  schedule:
  - cron: '0/5 * * * *'

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run: echo "Hello World Repeat 5 Secs"

