name: Shell Commands
on: [Push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: Echo
        run: echo "Hello World"
      - name: Multi
        run: |
          node -v
          npm -v
