name: Shell Commands
on: [pull_request]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: Echo
        run: echo "Hello World"
      - name: Multi
        run: |
          node -v
          npm -v
          pip -v
      - name: python cmd
        run: |
          import platform
          print (platform.processor())    
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Directory
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
      