name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: Echo
        run: echo "Hello World"
      - name: Multi
        run: |
          node -v
          npm -v
          pip -v
      - name: python cmd
        run: |
          import platform
          print (platform.processor())    
        shell: python